version: "3.9"

services:
  test-backend:
    image: nginxdemos/hello
    container_name: test-backend
    expose:
      - "80"

  nginx-cache:
    image: nginx:stable
    container_name: nginx-cache
    ports:
      - "80"
    volumes:
      - nginx_cache_data:/var/cache/nginx
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - test-backend

volumes:
  nginx_cache_data:
